import { state, getNativeLangName } from './state.js';
import { LANG_META } from './constants.js';
import { getVocab } from './vocab.js';

const { cfg } = state;

export function applyI18n(){
  const t=state.t;
  document.getElementById('hdr-title').textContent=t.appTitle;
  document.getElementById('settings-title').textContent=t.settingsTitle;
  document.getElementById('empty-title').textContent=t.emptyTitle;
  document.getElementById('empty-desc').textContent=t.emptyDesc;
  document.getElementById('quiz-empty-title').textContent=t.quizEmptyTitle;
  document.getElementById('quiz-empty-desc').textContent=t.quizEmptyDesc;
  document.getElementById('fb-lbl-positive').textContent=t.fbPositive;
  document.getElementById('fb-lbl-corrections').textContent=t.fbCorrections;
  document.getElementById('fb-lbl-suggestions').textContent=t.fbSuggestions;
  document.getElementById('nav-lbl-chat').textContent=t.navChat;
  document.getElementById('nav-lbl-vocab').textContent=t.navVocab;
  document.getElementById('nav-lbl-fc').textContent=t.navFc;
  document.getElementById('nav-lbl-quiz').textContent=t.navQuiz;
  document.getElementById('nav-lbl-settings').textContent=t.navSettings;
  document.getElementById('vocab-hdr-title').textContent=t.vocabHdr;
  document.getElementById('fc-hdr-title').textContent=t.fcHdr;
  document.getElementById('quiz-hdr-title').textContent=t.quizHdr;
  document.getElementById('sort-btn').textContent=t[['sortAlpha','sortDue','sortNew'][state.sortIdx]];
  const _dBtn=document.getElementById('fc-dir-btn');if(_dBtn){_dBtn.textContent=state.fcDirection==='normal'?t.fcDirNormal:t.fcDirReverse;_dBtn.classList.toggle('rev',state.fcDirection==='reverse');}
  const _fSel=document.getElementById('fc-filter-select');if(_fSel){const _fOpts=_fSel.querySelectorAll('option');if(_fOpts[0])_fOpts[0].textContent=t.fcFilterToday;if(_fOpts[1])_fOpts[1].textContent=t.fcFilterAll;if(_fOpts[2])_fOpts[2].textContent=t.fcFilterNew;if(_fOpts[3])_fOpts[3].textContent=t.fcFilterWeak;}
  document.getElementById('mode-lbl-chat').textContent=t.modeChat;
  document.getElementById('mode-lbl-lesson').textContent=t.modeLesson;
  document.getElementById('mode-btn-chat').title=t.modeChatDesc;
  document.getElementById('mode-btn-lesson').title=t.modeLessonDesc;
  document.getElementById('clear-chat-btn').title=t.clearChatTitle;
  document.getElementById('chat-help-btn').title=t.sHelpLink;
  updateModeBadge();
  updateInputPlaceholder();
  updateApiKeyHint();
  document.getElementById('s-provider-title').textContent=t.sProviderTitle;
  document.getElementById('s-provider-label').textContent=t.sProviderLabel;
  document.querySelector('#cfg-provider option[value="ollama"]').textContent=t.sOllamaOption;
  document.querySelector('#cfg-provider option[value="custom"]').textContent=t.sCustomOption;
  document.getElementById('s-model-label').textContent=t.sModelLabel;
  document.getElementById('fetch-models-lbl').textContent=t.fetchModelsLbl;
  document.getElementById('s-custom-model-label').textContent=t.sCustomModelLabel;
  document.getElementById('s-apikey-label').textContent=t.sApiKeyLabel;
  document.getElementById('s-ollama-hint').textContent=t.sOllamaHint;
  document.getElementById('s-anthropic-hint').textContent=t.sAnthropicHint;
  document.getElementById('s-advanced-label').textContent=t.sAdvancedLabel;
  document.getElementById('s-anthropic-proxy-label').textContent=t.sAnthropicProxyLabel;
  document.getElementById('s-anthropic-proxy-hint').textContent=t.sAnthropicProxyHint;
  document.getElementById('s-openai-endpoint-label').textContent=t.sOpenAIEndpointLabel;
  document.getElementById('s-openai-endpoint-hint').textContent=t.sOpenAIEndpointHint;
  document.getElementById('s-openai-auth-label').textContent=t.sOpenAIAuthLabel;
  document.getElementById('s-gemini-endpoint-label').textContent=t.sGeminiEndpointLabel;
  document.getElementById('s-gemini-endpoint-hint').textContent=t.sGeminiEndpointHint;
  document.getElementById('s-custom-url-hint').textContent=t.sCustomUrlHint;
  document.getElementById('s-tutor-title').textContent=t.sTutorTitle;
  document.getElementById('s-lang-label').textContent=t.sLangLabel;
  document.getElementById('s-level-label').textContent=t.sLevelLabel;
  document.querySelector('#cfg-level option[value="beginner"]').textContent=t.sLevelBeginner;
  document.querySelector('#cfg-level option[value="intermediate"]').textContent=t.sLevelIntermediate;
  document.querySelector('#cfg-level option[value="advanced"]').textContent=t.sLevelAdvanced;
  document.getElementById('s-feedback-label').textContent=t.sFeedbackLabel;
  document.querySelector('#cfg-feedback-style option[value="gentle"]').textContent=t.sFeedbackGentle;
  document.querySelector('#cfg-feedback-style option[value="balanced"]').textContent=t.sFeedbackBalanced;
  document.querySelector('#cfg-feedback-style option[value="strict"]').textContent=t.sFeedbackStrict;
  document.getElementById('s-custom-instructions-label').textContent=t.sCustomInstructionsLabel;
  document.getElementById('cfg-custom-instructions').placeholder=t.sCustomInstructionsPH;
  document.getElementById('s-custom-instructions-hint').textContent=t.sCustomInstructionsHint;
  document.getElementById('s-ui-title').textContent=t.sUiTitle;
  document.getElementById('s-ui-lang-label').textContent=t.sUiLangLabel;
  document.getElementById('s-native-lang-label').textContent=t.sNativeLangLabel;
  const _nlsOpt=document.querySelector('#cfg-native-lang option[value=""]');if(_nlsOpt)_nlsOpt.textContent=t.sNativeLangAuto;
  document.getElementById('s-font-size-label').textContent=t.sFontSizeLabel;
  document.querySelector('#cfg-font-size option[value="small"]').textContent=t.sFontSizeSmall;
  document.querySelector('#cfg-font-size option[value="medium"]').textContent=t.sFontSizeMedium;
  document.querySelector('#cfg-font-size option[value="large"]').textContent=t.sFontSizeLarge;
  document.querySelector('#cfg-font-size option[value="xl"]').textContent=t.sFontSizeXl;
  document.getElementById('s-theme-label').textContent=t.sThemeLabel;
  document.querySelector('#cfg-theme option[value="auto"]').textContent=t.themeAuto;
  document.querySelector('#cfg-theme option[value="light"]').textContent=t.themeLight;
  document.querySelector('#cfg-theme option[value="dark"]').textContent=t.themeDark;
  document.getElementById('s-default-view-label').textContent=t.sDefaultViewLabel;
  document.getElementById('s-default-view-vocab').textContent=t.navVocab;
  document.getElementById('s-default-view-quiz').textContent=t.navQuiz;
  document.getElementById('s-default-view-tips').textContent=t.navTips;
  document.getElementById('s-data-title').textContent=t.sDataTitle;
  document.getElementById('s-data-desc').textContent=t.sDataDesc;
  document.getElementById('s-save-btn').textContent=t.sSaveBtn;
  document.getElementById('s-export-btn').textContent=t.sExportBtn;
  document.getElementById('s-import-btn').textContent=t.sImportBtn;
  document.getElementById('backup-reminder-export-btn').textContent=t.backupReminderExport;
  document.getElementById('backup-reminder-later-btn').textContent=t.backupReminderLater;
  document.getElementById('backup-reminder-disable-btn').textContent=t.backupReminderDisable;
  document.getElementById('s-clear-btn').textContent=t.sClearBtn;
  document.getElementById('s-add-to-home').textContent=t.sAddToHome;
  document.getElementById('s-help-link').textContent=t.sHelpLink;
  document.getElementById('vocab-search').placeholder=t.vocabSearchPH;
  document.getElementById('vocab-gen-btn').textContent=t.vocabGenBtn;
  document.getElementById('delete-learned-btn').textContent=t.deleteLearnedBtn;
  document.getElementById('bulk-mode-btn').textContent=state.bulkSelectMode?t.bulkModeOff:t.bulkModeOn;
  document.getElementById('bulk-count').textContent=t.bulkCountFn(state.selectedIds.size);
  document.getElementById('bulk-select-all-btn').textContent=t.bulkSelectAll;
  document.getElementById('bulk-delete-btn').textContent=t.bulkDeleteBtn;
  document.getElementById('bulk-cancel-btn').textContent=t.bulkCancelBtn;
  document.getElementById('modal-trans').placeholder=t.modalTransPH;
  document.getElementById('modal-notes').placeholder=t.modalNotesPH;
  document.getElementById('modal-tags').placeholder=t.modalTagsPH;
  document.getElementById('import-text').placeholder=t.importTextPH;
  document.getElementById('gen-topic').placeholder=t.genTopicPH;
  const _langCode=LANG_META[state.vocabLang]?.lang||state.vocabLang;
  const _wordBase=t.modalWordLabel.replace(/\s*\*$/,'');
  document.getElementById('modal-word-label-text').textContent=`${_wordBase} (${_langCode}) *`;
  document.getElementById('modal-trans-label-text').textContent=t.modalTransLabel.replace(/\s*\*$/,'')+' ('+getNativeLangName()+') *';
  document.getElementById('modal-swap-btn').title=t.swapBtn;
  document.getElementById('modal-note-label').textContent=t.modalNoteLabel;
  document.getElementById('modal-tags-label').textContent=t.modalTagsLabel;
  document.getElementById('modal-sm2-title').textContent=t.modalSm2Title;
  document.getElementById('modal-save-btn').textContent=t.modalSaveBtn;
  document.getElementById('modal-cancel-btn').textContent=t.modalCancelBtn;
  document.getElementById('modal-delete-btn').textContent=t.modalDeleteBtn;
  document.getElementById('import-title').textContent=t.importTitle;
  document.getElementById('import-desc').innerHTML=t.importDesc;
  document.getElementById('import-content-label').textContent=t.importContentLabel;
  document.getElementById('import-lang-label').textContent=t.importLangLabel;
  document.getElementById('import-col-label').textContent=t.importColLabel;
  document.querySelector('#import-col-order option[value="normal"]').textContent=t.importColNormal;
  document.querySelector('#import-col-order option[value="reverse"]').textContent=t.importColReverse;
  document.getElementById('import-confirm-btn').textContent=t.importBtn;
  document.getElementById('import-cancel-btn').textContent=t.importCancelBtn;
  document.getElementById('import-file-btn').textContent=t.importFromFile;
  document.getElementById('backup-import-title').textContent=t.backupImportTitle;
  document.getElementById('backup-import-desc').textContent=t.backupImportDesc;
  document.getElementById('backup-import-label').textContent=t.backupImportLabel;
  document.getElementById('backup-import-btn').textContent=t.backupImportBtn;
  document.getElementById('backup-cancel-btn').textContent=t.backupCancelBtn;
  document.getElementById('backup-file-btn').textContent=t.backupFromFile;
  document.getElementById('gen-title').textContent=t.genTitle;
  document.getElementById('gen-topic-label').textContent=t.genTopicLabel;
  document.getElementById('gen-count-label').textContent=t.genCountLabel;
  document.getElementById('gen-level-label').textContent=t.genLevelLabel;
  document.querySelector('#gen-level option[value="beginner"]').textContent=t.sLevelBeginner;
  document.querySelector('#gen-level option[value="intermediate"]').textContent=t.sLevelIntermediate;
  document.querySelector('#gen-level option[value="advanced"]').textContent=t.sLevelAdvanced;
  document.getElementById('gen-cancel-btn').textContent=t.genCancelBtn;
  document.getElementById('gen-preview-hint').textContent=t.genPreviewHint;
  document.getElementById('gen-import-selected-btn').textContent=t.genImportSelectedBtn;
  document.getElementById('gen-back-btn').textContent=t.genBackBtn;
  document.getElementById('quiz-input').placeholder=t.quizAnswerPH;
  document.getElementById('pwa-banner-text').textContent=t.pwaBannerText;
  document.getElementById('pwa-install-btn').textContent=t.pwaInstallBtn;
  document.getElementById('pwa-guide-title').textContent=t.pwaGuideTitle;
  document.getElementById('pwa-guide-ios-s1').textContent=t.pwaGuideIosStep1;
  document.getElementById('pwa-guide-ios-s2').textContent=t.pwaGuideIosStep2;
  document.getElementById('pwa-guide-ios-s3').textContent=t.pwaGuideIosStep3;
  document.getElementById('pwa-guide-ios-warn').textContent=t.pwaGuideIosStorageWarn;
  document.getElementById('pwa-guide-close').textContent=t.pwaGuideClose;
  document.getElementById('sw-update-banner-text').textContent=t.swUpdateText;
  document.getElementById('sw-reload-btn').textContent=t.swReloadBtn;
  document.getElementById('add-word-btn').title=t.addWordTitle;
  document.getElementById('vocab-cost-warn').textContent=t.vocabCostWarn;
  document.getElementById('tips-hdr-title').textContent=t.tipsHdr;
  document.getElementById('nav-lbl-tips').textContent=t.navTips;
  document.getElementById('tips-lbl-positive').textContent=t.fbPositive;
  document.getElementById('tips-lbl-corrections').textContent=t.fbCorrections;
  document.getElementById('tips-lbl-suggestions').textContent=t.fbSuggestions;
  document.getElementById('tips-filter-all').textContent=t.tipsFilterAll;
  document.getElementById('tips-bulk-mode-btn').textContent=state.tipsBulkSelectMode?t.bulkModeOff:t.bulkModeOn;
  document.getElementById('dict-modal-title').textContent=t.dictModalTitle;
  document.getElementById('dict-input').placeholder=t.dictSearchPH;
  document.getElementById('dict-lookup-btn').textContent=t.dictLookupBtn;
  document.getElementById('dict-add-btn').textContent=t.dictAddBtn;
  document.getElementById('dict-close-btn').textContent=t.dictCloseBtn;
  document.getElementById('dict-btn').textContent=t.dictOpenBtn;
  document.getElementById('dict-warning').innerHTML=t.dictWarning;
  document.getElementById('footer-tagline').textContent=t.footerTagline;
  document.getElementById('pwa-dismiss-btn').title=t.bannerDismiss;
  document.getElementById('sw-dismiss-btn').title=t.bannerDismiss;
  const _ob=id=>document.getElementById(id);
  if(_ob('ob-title'))_ob('ob-title').textContent=t.onboardTitle;
  if(_ob('ob-step1')){const _ios=/iphone|ipad|ipod/i.test(navigator.userAgent)||(/macintosh/i.test(navigator.userAgent)&&navigator.maxTouchPoints>1);const _android=/android/i.test(navigator.userAgent);_ob('ob-step1').textContent=_ios?t.onboardStep1Ios:_android?t.onboardStep1Android:t.onboardStep1Desktop;}
  if(_ob('ob-step2'))_ob('ob-step2').textContent=t.onboardStep2;
  if(_ob('ob-step3'))_ob('ob-step3').textContent=t.onboardStep3;
  if(_ob('ob-dismiss'))_ob('ob-dismiss').textContent=t.onboardDismiss;
  if(_ob('ob-step4'))_ob('ob-step4').textContent=t.onboardStep4;
  document.getElementById('s-adv-btn').textContent='⚠ '+t.sAdvSettingsBtn;
  document.getElementById('adv-title').textContent='⚠ '+t.sAdvSettingsBtn;
  document.getElementById('adv-warning').textContent=t.advWarning;
  document.getElementById('adv-max-tokens-label').textContent=t.advMaxTokensLabel;
  document.getElementById('adv-max-tokens-hint').textContent=t.advMaxTokensHint;
  document.getElementById('adv-temperature-default-label').textContent=t.advTemperatureDefaultLabel;
  document.getElementById('adv-temperature-label').textContent=t.advTemperatureLabel;
  document.getElementById('adv-temperature-hint').textContent=t.advTemperatureHint;
  document.getElementById('adv-streaming-label').textContent=t.advStreamingLabel;
  document.getElementById('adv-streaming-hint').textContent=t.advStreamingHint;
  document.getElementById('adv-save-btn').textContent=t.advSaveBtn;
  document.getElementById('adv-cancel-btn').textContent=t.advCancelBtn;
  document.getElementById('adv-reset-btn').textContent=t.advResetBtn;
  document.getElementById('adv-cfg-edit-btn').textContent=t.advCfgEditBtn;
  document.getElementById('cfg-editor-title').textContent=t.cfgEditorTitle;
  document.getElementById('cfg-editor-hint').textContent=t.cfgEditorHint;
  document.getElementById('cfg-editor-save-btn').textContent=t.cfgEditorSaveBtn;
  document.getElementById('cfg-editor-cancel-btn').textContent=t.cfgEditorCancelBtn;
  document.getElementById('s-fc-session-size-label').textContent=t.sFcSessionSizeLabel;
  document.getElementById('s-fc-session-size-hint').textContent=t.sFcSessionSizeHint;
  document.getElementById('s-quiz-session-size-label').textContent=t.sQuizSessionSizeLabel;
  document.getElementById('s-quiz-session-size-hint').textContent=t.sQuizSessionSizeHint;
  document.getElementById('s-sm-easy-bonus-label').textContent=t.sSmEasyBonusLabel;
  document.getElementById('s-sm-easy-bonus-hint').textContent=t.sSmEasyBonusHint;
  document.getElementById('s-tts-rate-label').textContent=t.sTtsRateLabel;
  document.getElementById('s-tts-rate-hint').textContent=t.sTtsRateHint;
  document.getElementById('s-vocab-import-dups-label').textContent=t.sVocabImportDupsLabel;
  document.querySelector('#cfg-vocab-import-dups option[value="skip"]').textContent=t.sVocabImportDupsSkip;
  document.querySelector('#cfg-vocab-import-dups option[value="merge"]').textContent=t.sVocabImportDupsMerge;
  document.querySelector('#cfg-vocab-import-dups option[value="overwrite"]').textContent=t.sVocabImportDupsOverwrite;
  document.getElementById('s-vocab-import-dups-hint').textContent=t.sVocabImportDupsHint;
}

export function updateModeBadge(){
  const t=state.t;
  const chat=document.getElementById('mode-btn-chat');
  const lesson=document.getElementById('mode-btn-lesson');
  chat.classList.toggle('active',!cfg.lessonMode);
  lesson.classList.toggle('active',cfg.lessonMode);
  document.getElementById('vocab-cost-warn').style.display=(cfg.lessonMode&&getVocab(state.currentLang).length>40)?'block':'none';
}

export function updateInputPlaceholder(){
  const t=state.t;
  const m=LANG_META[state.currentLang];const label=m?(cfg.uiLang==='en'?m.name:m.native):state.currentLang;
  document.getElementById('msg-input').placeholder=t.inputPH(label);
}

export function updateEmptyState(){
  const m=LANG_META[state.currentLang];if(m)document.getElementById('empty-flag').textContent=m.flag;
}

export function updateApiKeyHint(){
  const t=state.t;
  const el=document.getElementById('apikey-hint');const h=t.apiHints[cfg.provider]||'';
  el.textContent=cfg.provider==='ollama'?(t.ollamaApiKeyHint||'Volitelné — vyžadováno pouze pokud je Ollama zabezpečena klíčem (OLLAMA_API_KEY) nebo reverse proxy.'):h?t.sGenerateAt(h):'';
  document.getElementById('apikey-storage-warn').textContent=cfg.provider!=='ollama'?t.apiKeyStorageWarn:'';
}
